runtime: nodejs18

env_variables:
  NODE_ENV: production

handlers:
  - url: /.*\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|otf|json)$
    static_files: dist/coludy-homework-front-end/\1
    upload: dist/coludy-homework-front-end/.*\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|otf|json)$

  - url: /.*
    static_files: dist/coludy-homework-front-end/index.html
    upload: dist/coludy-homework-front-end/index.html
