runtime: nodejs16

instance_class: F2

handlers:
- url: /
  static_files: dist/coludy-homework-front-end/index.html
  upload: dist/coludy-homework-front-end/index.html

- url: /
  static_dir: dist/coludy-homework-front-end
